doctrine:
    dbal:
        # Configuration de la connexion à la base de données
        default_connection: default
        connections:
            default:
                # Configuration spécifique à SQL Server
                driver: 'pdo_sqlsrv'
                # Hôte du serveur SQL Server
                host: '5.196.92.101'
                # Port (par défaut : 1433)
                port: '1433'
                # Nom de la base de données
                dbname: 'RFT_V1'
                # Nom d'utilisateur
                user: 'sa'
                # Mot de passe
                password: '@Serv+sol24+#05'
                # Options supplémentaires
                charset: 'UTF-8'
                options:
                    TrustServerCertificate: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
